import { useState, useRef, useEffect } from "react";
import {
  X,
  Layers,
  Cpu,
  Activity,
  Zap,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  ExternalLink,
  CheckCircle2,
  Maximize2,
  Minimize2,
  Compass,
} from "lucide-react";
import type { Operation, TelemetryData } from "../types";

export type InspectableUnit =
  | "hcla"
  | "booth"
  | "shifter"
  | "logic"
  | "comparator"
  | "telemetry"
  | "reversible"
  | "ports";

interface CircuitInspectorModalProps {
  unitKey: InspectableUnit;
  operation: Operation;
  a: number;
  b: number;
  result: number;
  zero: boolean;
  negative: boolean;
  carry: boolean;
  overflow: boolean;
  telemetry: TelemetryData;
  onClose: () => void;
}

interface SchematicItem {
  id: string;
  name: string;
  svgPath: string;
  description: string;
  tag: string;
}

const SCHEMATICS_MAP: Record<InspectableUnit, SchematicItem[]> = {
  hcla: [
    {
      id: "hcla_clean",
      name: "32-Bit HCLA Circuit Diagram",
      svgPath: "/schematics/hcla_clean_schematic.jpg",
      description: "Square 1:1 logic circuit diagram of the 32-bit Hierarchical Carry-Lookahead Adder with 8 CLA4 blocks and central lookahead carry generator.",
      tag: "Engineered 1:1",
    },
    {
      id: "cla4_clean",
      name: "4-Bit CLA Block Logic Gates",
      svgPath: "/schematics/cla4_clean_schematic.jpg",
      description: "Gate-level logic diagram showing XOR propagate gates, AND generate gates, and parallel AND-OR lookahead carry tree.",
      tag: "Logic Gates",
    },
    {
      id: "hcla_yosys",
      name: "Yosys Netlist (HCLA 32-bit)",
      svgPath: "/schematics/HierarchicalCarryLookaheadAdder.svg",
      description: "Gate-level netlist generated directly by Yosys from Chisel SystemVerilog RTL.",
      tag: "RTL Netlist",
    },
    {
      id: "cla4_yosys",
      name: "Yosys Netlist (CLA4 Block)",
      svgPath: "/schematics/CLA4.svg",
      description: "Synthesized 4-bit CLA module netlist.",
      tag: "RTL Netlist",
    },
  ],
  booth: [
    {
      id: "booth_clean",
      name: "Booth-Wallace Multiplier Circuit",
      svgPath: "/schematics/booth_wallace_clean_schematic.jpg",
      description: "Square 1:1 logic schematic showing Radix-4 Booth recoding, partial product multiples, 3:2 Wallace CSA compressor reduction tree, and final CLA vector adder.",
      tag: "Engineered 1:1",
    },
    {
      id: "booth_yosys",
      name: "Yosys Netlist (Booth-Wallace)",
      svgPath: "/schematics/BoothWallaceMultiplier.svg",
      description: "Full synthesized multiplier netlist generated by Yosys.",
      tag: "RTL Netlist",
    },
    {
      id: "booth_radix4_yosys",
      name: "Yosys Netlist (Radix-4 Booth)",
      svgPath: "/schematics/BoothMultiplier.svg",
      description: "Synthesized Radix-4 Booth multiplier module.",
      tag: "RTL Netlist",
    },
  ],
  shifter: [
    {
      id: "shifter_clean",
      name: "32-Bit Barrel Shifter Circuit",
      svgPath: "/schematics/barrel_shifter_clean_schematic.jpg",
      description: "Square 1:1 logic circuit diagram of the 5-stage logarithmic barrel shifter (shifts 1, 2, 4, 8, 16) supporting SLL, SRL, and SRA with sign-extension logic.",
      tag: "Engineered 1:1",
    },
    {
      id: "alu_yosys",
      name: "Yosys Netlist (ALU Shifter)",
      svgPath: "/schematics/ALU.svg",
      description: "Full ALU datapath netlist containing shifter multiplexers.",
      tag: "RTL Netlist",
    },
  ],
  logic: [
    {
      id: "alu_arch_clean",
      name: "ALU & Logic Fabric Architecture",
      svgPath: "/schematics/alu_clean_schematic.jpg",
      description: "Square 1:1 architecture diagram of the 32-bit ALU with parallel bitwise logic fabric (AND, OR, XOR), opcode decoder, and multiplexer.",
      tag: "Engineered 1:1",
    },
    {
      id: "alu_yosys",
      name: "Yosys Netlist (ALU Logic)",
      svgPath: "/schematics/ALU.svg",
      description: "Complete synthesized ALU gate netlist.",
      tag: "RTL Netlist",
    },
  ],
  comparator: [
    {
      id: "alu_arch_clean",
      name: "ALU Comparator & Subtractor",
      svgPath: "/schematics/alu_clean_schematic.jpg",
      description: "Square 1:1 architecture diagram showing signed SLT (N ⊕ V) and unsigned SLTU (¬C) comparator paths within the ALU.",
      tag: "Engineered 1:1",
    },
    {
      id: "alu_yosys",
      name: "Yosys Netlist (ALU Comparator)",
      svgPath: "/schematics/ALU.svg",
      description: "Synthesized ALU netlist with comparator flag logic.",
      tag: "RTL Netlist",
    },
  ],
  telemetry: [
    {
      id: "telemetry_clean",
      name: "Hardware Telemetry & EDP Engine",
      svgPath: "/schematics/telemetry_clean_schematic.jpg",
      description: "Square 1:1 digital logic diagram showing the 32-bit bitwise XOR array, PopCount Hamming-distance adder tree, accumulator registers, and EDP hardware multiplier.",
      tag: "Engineered 1:1",
    },
    {
      id: "telemetry_yosys",
      name: "Yosys Netlist (TelemetryBlock)",
      svgPath: "/schematics/TelemetryBlock.svg",
      description: "Synthesized netlist of the hardware telemetry block.",
      tag: "RTL Netlist",
    },
    {
      id: "subsystem_yosys",
      name: "Yosys Netlist (Objective1Subsystem)",
      svgPath: "/schematics/Objective1Subsystem.svg",
      description: "Top-level subsystem wrapper with memory-mapped address decoder at 0x80001000.",
      tag: "RTL Netlist",
    },
  ],
  reversible: [
    {
      id: "reversible_clean",
      name: "Fredkin & Toffoli Reversible Gates",
      svgPath: "/schematics/reversible_clean_schematic.jpg",
      description: "Square 1:1 digital logic schematic of the Fredkin Controlled-SWAP gate and Toffoli Controlled-Controlled-NOT gate with standard logic gate and multiplexer symbols.",
      tag: "Engineered 1:1",
    },
    {
      id: "fredkin_yosys",
      name: "Yosys Netlist (Fredkin Gate)",
      svgPath: "/schematics/Fredkin.svg",
      description: "Gate-level netlist of the Fredkin module.",
      tag: "RTL Netlist",
    },
    {
      id: "toffoli_yosys",
      name: "Yosys Netlist (Toffoli Gate)",
      svgPath: "/schematics/Toffoli.svg",
      description: "Gate-level netlist of the Toffoli module.",
      tag: "RTL Netlist",
    },
  ],
  ports: [
    {
      id: "alu_arch_clean",
      name: "ALU Architecture & Datapath",
      svgPath: "/schematics/alu_clean_schematic.jpg",
      description: "Square 1:1 digital logic diagram of the 32-bit ALU showing operand inputs, functional units, condition flag generator, and result multiplexer.",
      tag: "Engineered 1:1",
    },
    {
      id: "subsystem_yosys",
      name: "Yosys Netlist (Objective1Subsystem)",
      svgPath: "/schematics/Objective1Subsystem.svg",
      description: "Top-level netlist showing all I/O ports and telemetry registers.",
      tag: "RTL Netlist",
    },
  ],
};

function hex32(n: number) {
  return (n >>> 0).toString(16).padStart(8, "0").toUpperCase();
}

function bin32(n: number) {
  return (n >>> 0).toString(2).padStart(32, "0");
}

export function CircuitInspectorModal({
  unitKey,
  operation,
  a,
  b,
  result,
  zero,
  negative,
  carry,
  overflow,
  telemetry,
  onClose,
}: CircuitInspectorModalProps) {
  const [activeTab, setActiveTab] = useState<"schematic" | "logic" | "signals" | "rtl">("schematic");
  const schematics = SCHEMATICS_MAP[unitKey] || SCHEMATICS_MAP.hcla;
  const [selectedSchematic, setSelectedSchematic] = useState<SchematicItem>(schematics[0]);

  // Pan & Zoom state
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const [isFullscreen, setIsFullscreen] = useState(false);
  const viewerRef = useRef<HTMLDivElement>(null);

  // Reset schematic selection when unitKey changes
  useEffect(() => {
    const list = SCHEMATICS_MAP[unitKey] || SCHEMATICS_MAP.hcla;
    setSelectedSchematic(list[0]);
    setZoom(1);
    setPan({ x: 0, y: 0 });
  }, [unitKey]);

  const handleZoomIn = () => setZoom((z) => Math.min(z * 1.35, 6));
  const handleZoomOut = () => setZoom((z) => Math.max(z / 1.35, 0.4));
  const handleResetZoom = () => {
    setZoom(1);
    setPan({ x: 0, y: 0 });
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    if (e.button !== 0) return;
    setIsDragging(true);
    setDragStart({ x: e.clientX - pan.x, y: e.clientY - pan.y });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return;
    setPan({
      x: e.clientX - dragStart.x,
      y: e.clientY - dragStart.y,
    });
  };

  const handleMouseUp = () => setIsDragging(false);

  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault();
    const factor = e.deltaY < 0 ? 1.15 : 0.88;
    setZoom((z) => Math.max(0.3, Math.min(8, z * factor)));
  };

  return (
    <div className={`modal-overlay ${isFullscreen ? "fullscreen-overlay" : ""}`} onClick={onClose}>
      <div
        className={`modal-container ${isFullscreen ? "fullscreen-modal" : ""}`}
        onClick={(e) => e.stopPropagation()}
      >
        <header className="modal-header">
          <div className="modal-title-wrap">
            <span className="modal-badge">RTL LOGIC SCHEMATIC &amp; CIRCUIT INSPECTOR</span>
            <h2>{getTitle(unitKey)}</h2>
          </div>
          <div className="modal-actions">
            <div className="modal-tabs">
              <button
                className={`modal-tab ${activeTab === "schematic" ? "active" : ""}`}
                onClick={() => setActiveTab("schematic")}
              >
                <Cpu size={14} /> Logic Schematic
              </button>
              <button
                className={`modal-tab ${activeTab === "logic" ? "active" : ""}`}
                onClick={() => setActiveTab("logic")}
              >
                <Layers size={14} /> Equations &amp; Math
              </button>
              <button
                className={`modal-tab ${activeTab === "signals" ? "active" : ""}`}
                onClick={() => setActiveTab("signals")}
              >
                <Activity size={14} /> Live Probes
              </button>
              <button
                className={`modal-tab ${activeTab === "rtl" ? "active" : ""}`}
                onClick={() => setActiveTab("rtl")}
              >
                <Zap size={14} /> Chisel / Verilog
              </button>
            </div>
            <button
              className="modal-icon-btn"
              onClick={() => setIsFullscreen(!isFullscreen)}
              title={isFullscreen ? "Exit Fullscreen" : "Fullscreen View"}
            >
              {isFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
            </button>
            <button className="modal-close-btn" onClick={onClose} aria-label="Close modal">
              <X size={18} />
            </button>
          </div>
        </header>

        <div className="modal-body">
          {activeTab === "schematic" && (
            <div className="schematic-tab-content">
              {/* Schematic selector sub-bar */}
              <div className="schematic-selector-bar">
                <div className="schematic-pills">
                  {schematics.map((s) => (
                    <button
                      key={s.id}
                      className={`schematic-pill ${selectedSchematic.id === s.id ? "active" : ""}`}
                      onClick={() => {
                        setSelectedSchematic(s);
                        handleResetZoom();
                      }}
                    >
                      <span className="pill-tag">{s.tag}</span>
                      <span className="pill-name">{s.name}</span>
                    </button>
                  ))}
                </div>

                <div className="schematic-controls">
                  <span className="zoom-indicator">{Math.round(zoom * 100)}%</span>
                  <button onClick={handleZoomIn} title="Zoom In" className="ctrl-btn">
                    <ZoomIn size={14} />
                  </button>
                  <button onClick={handleZoomOut} title="Zoom Out" className="ctrl-btn">
                    <ZoomOut size={14} />
                  </button>
                  <button onClick={handleResetZoom} title="Reset Zoom" className="ctrl-btn">
                    <RotateCcw size={14} />
                  </button>
                  <a
                    href={selectedSchematic.svgPath}
                    target="_blank"
                    rel="noreferrer"
                    className="ctrl-btn link-btn"
                    title="Open Full Image / SVG in New Tab"
                  >
                    <ExternalLink size={14} /> Full View
                  </a>
                </div>
              </div>

              {/* Interactive Vector Canvas */}
              <div
                ref={viewerRef}
                className={`svg-pan-viewport ${isDragging ? "dragging" : ""}`}
                onMouseDown={handleMouseDown}
                onMouseMove={handleMouseMove}
                onMouseUp={handleMouseUp}
                onMouseLeave={handleMouseUp}
                onWheel={handleWheel}
              >
                <div
                  className="svg-pan-canvas"
                  style={{
                    transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
                    transformOrigin: "center center",
                  }}
                >
                  <img
                    src={selectedSchematic.svgPath}
                    alt={selectedSchematic.name}
                    className="schematic-svg-image square-schematic"
                    draggable={false}
                  />
                </div>
                <div className="pan-hint">
                  <Compass size={12} /> Drag to pan · Scroll wheel to zoom · Click tabs above to switch diagrams
                </div>
              </div>

              <div className="schematic-meta-footer">
                <p>
                  <strong>{selectedSchematic.name}:</strong> {selectedSchematic.description}
                </p>
                <span className="source-label">
                  Standard IEEE Logic Symbols · Square 1:1 Composition · Synchronized with <code>Objective1Subsystem.sv</code>
                </span>
              </div>
            </div>
          )}

          {activeTab === "logic" && renderLogic(unitKey, a, b, result, operation)}
          {activeTab === "signals" &&
            renderSignals(unitKey, a, b, result, zero, negative, carry, overflow, telemetry, operation)}
          {activeTab === "rtl" && renderRTL(unitKey)}
        </div>

        <footer className="modal-footer">
          <div className="modal-footer-note">
            <CheckCircle2 size={14} className="text-emerald" />
            <span>
              Engineered logic gate schematics with clean orthogonal layout and IEEE symbols.
            </span>
          </div>
          <button className="btn-secondary" onClick={onClose}>
            Close Inspector
          </button>
        </footer>
      </div>
    </div>
  );
}

function getTitle(unitKey: InspectableUnit): string {
  switch (unitKey) {
    case "hcla":
      return "Hierarchical Carry-Lookahead Adder (32-bit / 8 × CLA4)";
    case "booth":
      return "Radix-4 Booth Multiplier with Wallace Tree Reduction";
    case "shifter":
      return "Logarithmic Barrel Shifter (SLL / SRL / SRA)";
    case "logic":
      return "32-Bit Parallel Logic Fabric (AND / OR / XOR)";
    case "comparator":
      return "Signed / Unsigned Magnitude Comparator (SLT / SLTU)";
    case "telemetry":
      return "Memory-Mapped Telemetry Block & EDP Proxy Engine";
    case "reversible":
      return "Reversible Computing Gates (Fredkin & Toffoli)";
    case "ports":
      return "Objective 1 Subsystem Top-Level Architecture & Netlists";
  }
}

function renderLogic(unitKey: InspectableUnit, a: number, b: number, result: number, operation: Operation) {
  switch (unitKey) {
    case "hcla":
      return (
        <div className="logic-math-panel">
          <h3>Carry-Lookahead Mathematical Equations</h3>
          <div className="math-block">
            <p><strong>1. Bit Generate &amp; Propagate terms:</strong></p>
            <code>P_i = A_i ⊕ B_i</code>
            <code>G_i = A_i · B_i</code>
          </div>
          <div className="math-block">
            <p><strong>2. 4-Bit Block Lookahead (CLA4):</strong></p>
            <code>C_1 = G_0 + P_0 · C_0</code>
            <code>C_2 = G_1 + P_1 · G_0 + P_1 · P_0 · C_0</code>
            <code>C_3 = G_2 + P_2 · G_1 + P_2 · P_1 · G_0 + P_2 · P_1 · P_0 · C_0</code>
            <code>C_4 = G_3 + P_3 · G_2 + P_3 · P_2 · G_1 + P_3 · P_2 · P_1 · G_0 + P_3 · P_2 · P_1 · P_0 · C_0</code>
          </div>
          <div className="math-block">
            <p><strong>3. Hierarchical Block Group Terms (Level 2):</strong></p>
            <code>P_G = P_3 · P_2 · P_1 · P_0</code>
            <code>G_G = G_3 + P_3 · G_2 + P_3 · P_2 · G_1 + P_3 · P_2 · P_1 · G_0</code>
          </div>
          <div className="math-block">
            <p><strong>4. Subtraction Two&apos;s Complement Mode:</strong></p>
            <code>Sub = A + (~B) + 1  (Cin = 1, CarryOut = 1 means No Borrow)</code>
          </div>
        </div>
      );

    case "booth":
      return (
        <div className="logic-math-panel">
          <h3>Radix-4 Booth Encoding &amp; Wallace Tree Rules</h3>
          <div className="table-wrapper">
            <table className="data-table">
              <thead>
                <tr>
                  <th>b(2i+1)</th>
                  <th>b(2i)</th>
                  <th>b(2i-1)</th>
                  <th>Multiplier Factor</th>
                  <th>Action on Multiplicand A</th>
                </tr>
              </thead>
              <tbody>
                <tr><td>0</td><td>0</td><td>0</td><td>0</td><td>0 (Zero partial product)</td></tr>
                <tr><td>0</td><td>0</td><td>1</td><td>+1</td><td>+A</td></tr>
                <tr><td>0</td><td>1</td><td>0</td><td>+1</td><td>+A</td></tr>
                <tr><td>0</td><td>1</td><td>1</td><td>+2</td><td>+2A (Shift A left 1 bit)</td></tr>
                <tr><td>1</td><td>0</td><td>0</td><td>-2</td><td>-2A (Two&apos;s complement negate &amp; shift left 1)</td></tr>
                <tr><td>1</td><td>0</td><td>1</td><td>-1</td><td>-A (Two&apos;s complement negate)</td></tr>
                <tr><td>1</td><td>1</td><td>0</td><td>-1</td><td>-A (Two&apos;s complement negate)</td></tr>
                <tr><td>1</td><td>1</td><td>1</td><td>0</td><td>0 (Zero partial product)</td></tr>
              </tbody>
            </table>
          </div>
          <div className="math-block">
            <p><strong>Wallace Tree 3:2 Carry-Save Compressor:</strong></p>
            <code>Sum = A ⊕ B ⊕ C</code>
            <code>Carry = ((A · B) | (A · C) | (B · C)) &lt;&lt; 1</code>
            <p style={{ marginTop: "8px" }}><strong>Final Carry-Propagate Addition:</strong></p>
            <code>io.result := currentRows(0) +& currentRows(1)  (WallaceTree.scala)</code>
          </div>
        </div>
      );

    case "shifter":
      return (
        <div className="logic-math-panel">
          <h3>Variable Shifter Implementation &amp; Synthesis Model</h3>
          <div className="math-block">
            <p><strong>1. Chisel RTL Implementation (ALU.scala):</strong></p>
            <code>SLL: io.a &lt;&lt; shiftAmount (Dynamic logical left shift)</code>
            <code>SRL: io.a &gt;&gt; shiftAmount (Dynamic logical right shift with zero fill)</code>
            <code>SRA: io.a.asSInt &gt;&gt; shiftAmount (Arithmetic right shift with sign extension)</code>
          </div>
          <div className="math-block">
            <p><strong>2. Representative Synthesized Architecture:</strong></p>
            <p>Variable shifts synthesize into a 5-stage logarithmic multiplexer barrel shifter (stages for 1, 2, 4, 8, and 16 bits) controlled by B[4:0].</p>
          </div>
        </div>
      );

    case "comparator":
      return (
        <div className="logic-math-panel">
          <h3>Magnitude Comparator Implementation</h3>
          <div className="math-block">
            <p><strong>1. Direct Chisel Expressions (ALU.scala):</strong></p>
            <code>Signed SLT:  io.a.asSInt &lt; io.b.asSInt</code>
            <code>Unsigned SLTU: io.a &lt; io.b</code>
          </div>
          <div className="math-block">
            <p><strong>2. Subtractor Flag Equivalence:</strong></p>
            <p>Architecturally equivalent to subtractor flags (SLT = N ⊕ V, SLTU = ¬C), directly evaluated in hardware.</p>
          </div>
        </div>
      );

    case "telemetry":
      return (
        <div className="logic-math-panel">
          <h3>Result-Bus Telemetry &amp; Activity Measurement</h3>
          <div className="math-block">
            <p><strong>1. Result-Bus Hamming Distance Activity Metric:</strong></p>
            <code>Activity = PopCount(Result_t ⊕ Result_&#123;t-1&#125;)</code>
            <p>Measures bit transitions on the 32-bit ALU output bus during active cycles.</p>
          </div>
          <div className="math-block">
            <p><strong>2. Activity-Based Energy Proxy:</strong></p>
            <code>Energy_Proxy = REV_ENERGY_ACC + CLA_SWITCHING + MUL_THERMAL</code>
          </div>
          <div className="math-block">
            <p><strong>3. Energy-Delay Product (EDP) Activity Proxy:</strong></p>
            <code>EDP_CURRENT = Energy_Proxy × EDP_CONFIG  (where EDP_CONFIG = 1)</code>
          </div>
          <div className="math-block">
            <p><strong>4. Memory-Mapped Address Map (0x80001000):</strong></p>
            <code>0x80001000: REV_ENERGY_ACC  (Reserved reversible counter; fixed to 0)</code>
            <code>0x80001004: CLA_SWITCHING   (Result-bus Hamming distance on ADD/SUB)</code>
            <code>0x80001008: MUL_THERMAL     (Result-bus Hamming distance on MUL)</code>
            <code>0x8000100C: EDP_CURRENT     (Current EDP activity proxy)</code>
            <code>0x80001010: EDP_CONFIG      (Scale constant fixed to 1; read-only)</code>
          </div>
        </div>
      );

    default:
      return (
        <div className="logic-math-panel">
          <h3>ALU Operation Specification</h3>
          <div className="math-block">
            <p><strong>Current Selected Opcode {operation.opcode}: {operation.label}</strong></p>
            <code>{operation.description}</code>
            <code>Status Flags: Zero = (Result == 0), Negative = Result[31], Carry = Adder.Cout</code>
          </div>
        </div>
      );
  }
}

function renderSignals(
  unitKey: InspectableUnit,
  a: number,
  b: number,
  result: number,
  zero: boolean,
  negative: boolean,
  carry: boolean,
  overflow: boolean,
  telemetry: TelemetryData,
  operation: Operation
) {
  return (
    <div className="signals-probe-panel">
      <h3>Live Hardware Signal Probes (Current Cycle)</h3>
      <div className="probes-grid">
        <div className="probe-card">
          <span className="probe-name">Input A (32-bit / 0x{hex32(a)})</span>
          <span className="probe-hex">0x{hex32(a)}</span>
          <span className="probe-bin">{bin32(a)}</span>
        </div>
        <div className="probe-card">
          <span className="probe-name">Input B (32-bit / 0x{hex32(b)})</span>
          <span className="probe-hex">0x{hex32(b)}</span>
          <span className="probe-bin">{bin32(b)}</span>
        </div>
        <div className="probe-card highlight">
          <span className="probe-name">Output Result (32-bit / 0x{hex32(result)})</span>
          <span className="probe-hex">0x{hex32(result)}</span>
          <span className="probe-bin">{bin32(result)}</span>
        </div>
        <div className="probe-card">
          <span className="probe-name">Hardware Condition Flags</span>
          <div className="flags-row">
            <span className={`flag-badge ${zero ? "active" : ""}`}>Z={zero ? "1" : "0"}</span>
            <span className={`flag-badge ${negative ? "active" : ""}`}>N={negative ? "1" : "0"}</span>
            <span className={`flag-badge ${carry ? "active" : ""}`}>C={carry ? "1" : "0"}</span>
            <span className={`flag-badge ${overflow ? "active" : ""}`}>V={overflow ? "1" : "0"}</span>
          </div>
        </div>
        <div className="probe-card">
          <span className="probe-name">CLA Switching Transitions</span>
          <span className="probe-val">{telemetry.cla_switching}</span>
        </div>
        <div className="probe-card">
          <span className="probe-name">Multiplier Thermal Activity</span>
          <span className="probe-val">{telemetry.mul_thermal}</span>
        </div>
        <div className="probe-card">
          <span className="probe-name">EDP Proxy Current</span>
          <span className="probe-val">{telemetry.edp_current}</span>
        </div>
        <div className="probe-card">
          <span className="probe-name">Active Opcode</span>
          <span className="probe-val">{operation.opcode} ({operation.label})</span>
        </div>
      </div>
    </div>
  );
}

function renderRTL(unitKey: InspectableUnit) {
  let filename = "ALU.scala";
  let snippet = "";

  switch (unitKey) {
    case "hcla":
      filename = "HierarchicalCarryLookaheadAdder.scala";
      snippet = `package objective01.arithmetic

import chisel3._

class CLA4 extends Module {
  val io = IO(new Bundle {
    val a = Input(UInt(4.W))
    val b = Input(UInt(4.W))
    val carryIn = Input(Bool())
    val sum = Output(UInt(4.W))
    val carryOut = Output(Bool())
    val groupPropagate = Output(Bool())
    val groupGenerate = Output(Bool())
  })
  // 4-bit block CLA logic with propagate and generate gates...
}

class HierarchicalCarryLookaheadAdder(val width: Int) extends Module {
  require(width > 0 && width % 4 == 0, "Hierarchical CLA width must be a positive multiple of four")
  private val blocks = width / 4
  val io = IO(new Bundle {
    val a = Input(UInt(width.W))
    val b = Input(UInt(width.W))
    val carryIn = Input(Bool())
    val sum = Output(UInt(width.W))
    val carryOut = Output(Bool())
  })
  // 8 x CLA4 modules + 2nd-level Lookahead Generator...
}`;
      break;
    case "booth":
      filename = "BoothWallaceMultiplier.scala";
      snippet = `package objective01.arithmetic

import chisel3._
import chisel3.util._

class BoothWallaceMultiplier(val width: Int) extends Module {
  require(width > 0 && width % 2 == 0, "BoothWallaceMultiplier width must be positive and even")
  private val productWidth = 2 * width
  private val accumulatorWidth = productWidth + 2
  private val groups = width / 2

  val io = IO(new Bundle {
    val a = Input(UInt(width.W))
    val b = Input(UInt(width.W))
    val product = Output(UInt(productWidth.W))
  })

  // Radix-4 Booth partial product generation + Wallace Tree carry-save reduction...
}`;
      break;
    case "telemetry":
      filename = "TelemetryBlock.scala";
      snippet = `package objective01.telemetry

import chisel3._
import chisel3.util._

object TelemetryAddress {
  val Base = "h80001000".U(32.W)
  val RevEnergyAcc = "h80001000".U(32.W)
  val ClaSwitching = "h80001004".U(32.W)
  val MulThermal = "h80001008".U(32.W)
  val EdpCurrent = "h8000100c".U(32.W)
  val EdpConfig = "h80001010".U(32.W)
}

class TelemetryBlock(val width: Int) extends Module {
  val reversibleEnergy = RegInit(0.U(32.W))
  val claSwitching = RegInit(0.U(32.W))
  val multiplierThermal = RegInit(0.U(32.W))
  val edpConfig = RegInit(1.U(32.W))
  val previousResult = RegInit(0.U(width.W))

  val changedBits = PopCount(io.result ^ previousResult)
  val activity = Mux(io.operationValid, changedBits, 0.U)
  val energyProxy = reversibleEnergy +& claSwitching +& multiplierThermal
  val edpProxy = energyProxy * edpConfig
}`;
      break;
    default:
      filename = "ALU.scala";
      snippet = `package objective01.datapath

import chisel3._
import chisel3.util._
import objective01.arithmetic.{BoothWallaceMultiplier, HierarchicalCarryLookaheadAdder}

class ALU(val width: Int) extends Module {
  val io = IO(new Bundle {
    val a = Input(UInt(width.W))
    val b = Input(UInt(width.W))
    val opcode = Input(UInt(4.W))
    val result = Output(UInt(width.W))
    val zero = Output(Bool())
    val negative = Output(Bool())
    val carry = Output(Bool())
    val overflow = Output(Bool())
    val busy = Output(Bool())
    val done = Output(Bool())
    val valid = Output(Bool())
  })
  // 11 RISC-V compatible opcodes...
}`;
  }

  return (
    <div className="rtl-code-panel">
      <div className="code-header">
        <span>File: <code>objective01-digital-logic/src/main/scala/{filename}</code></span>
      </div>
      <pre className="code-content">
        <code>{snippet}</code>
      </pre>
    </div>
  );
}
